### ISSUE TITLE
[Problem] Can I use it in gitlab runner?

### ISSUE THREAD

**Issue by Tumb1eweed** [multiarch/qemu-user-static#190]
I want to use "docker run --rm --privileged multiarch/qemu-user-static --reset -p yes -c yes" to set up environment for a aarch64 docker image in x86, can it be done in gitlab runner?

**Comment by martin-g** [comment]
Yes

**Comment by Tumb1eweed** [comment]
> Yes

Is there an example? A .gitlab-ci.yml would be great.

**Comment by martin-g** [comment]
Friendly advise: when you ask for help from volunteers (OSS is based on volunteer work!) you should try to help yourself first and then ask others to help you!
That is:
- try to provide as much information as you have about what you want to achieve
- tell us what you have tried so far
- tell us what failed and how

Such kind of information is very valuable! 
Otherwise you look like a lazy person who didn't even bother to make a simple Google search.
Here is an article that explains how to use `qemu-user-static` - https://martin-grigorov.medium.com/building-linux-packages-for-different-cpu-architectures-with-docker-and-qemu-d29e4ebc9fa5
There is nothing Gitlab specific in qemu-user-static, so there is nothing to document about it.  Just run a x86_64 VM in Gitlab, then register QEMU and then run the aarch64 Docker container.

**Comment by Tumb1eweed** [comment]
> Friendly advise: when you ask for help from volunteers (OSS is based on volunteer work!) you should try to help yourself first and then ask others to help you! That is:
> 
> * try to provide as much information as you have about what you want to achieve
> * tell us what you have tried so far
> * tell us what failed and how
> 
> Such kind of information is very valuable! Otherwise you look like a lazy person who didn't even bother to make a simple Google search. Here is an article that explains how to use `qemu-user-static` - https://martin-grigorov.medium.com/building-linux-packages-for-different-cpu-architectures-with-docker-and-qemu-d29e4ebc9fa5 There is nothing Gitlab specific in qemu-user-static, so there is nothing to document about it. Just run a x86_64 VM in Gitlab, then register QEMU and then run the aarch64 Docker container.

Thanks, I find the relative merge about this: https://gitlab.com/gitlab-org/gitlab-runner/-/merge_requests/1861.
I forget to add use qemu-user-static in gitlab runner, sorry for that.
