### ISSUE TITLE
qemu: uncaught target signal 5

### ISSUE THREAD

**Issue by RaymondMouthaan** [multiarch/qemu-user-static#39]
Hello @lafin,

When running my travis job with qemu version 2.12.0 (arm) the following error occured, while running with 2.9.1-1 it succeeds.

```
Step 19/23 : RUN npm install
 ---> Running in 0a4abea8c736
#
# Fatal error in , line 0
# Missing deoptimization information for OptimizedFrame::Summarize.
#
qemu: uncaught target signal 5 (Trace/breakpoint trap) - core dumped
Trace/breakpoint trap (core dumped)
The command '/bin/sh -c npm install' returned a non-zero code: 133
```

Can you please have a look?

Thanks in advance,
Ray

**Comment by lafin** [comment]
I'm not sure then I can help you. Because We just use prebuilt binary qemu and if you saw an error on newest version qemu which not shown on the older version that can fix only maintainers of qemu. Anyway, I saw your images. You use the different version of qemu for base image and subsidiary image. Probably it's doing some side effect.

**Comment by RaymondMouthaan** [comment]
Woow you right about that! Totally missed that 😅 ... I will remove qemu static old before copy the newest and see if that helps!

**Comment by RaymondMouthaan** [comment]
@lafin removing previous qemu-*-static before copying newest fixed it!

Thanks for pointing me in the right direction 💯 .
