### ISSUE TITLE
How to enable i386?

### ISSUE THREAD

**Issue by vk496** [multiarch/qemu-user-static#81]
**Is this a bug report, feature (enhancement) request or question? (leave only one on its own line)**

/kind question

**Description:**

How can I register the qemu-static-i386?

**Steps to reproduce the issue:**

1. 

```bash
$ docker run --rm --privileged multiarch/qemu-user-static --reset -p yes          
Setting /usr/bin/qemu-alpha-static as binfmt interpreter for alpha
Setting /usr/bin/qemu-arm-static as binfmt interpreter for arm
Setting /usr/bin/qemu-armeb-static as binfmt interpreter for armeb
Setting /usr/bin/qemu-sparc32plus-static as binfmt interpreter for sparc32plus
Setting /usr/bin/qemu-ppc-static as binfmt interpreter for ppc
Setting /usr/bin/qemu-ppc64-static as binfmt interpreter for ppc64
Setting /usr/bin/qemu-ppc64le-static as binfmt interpreter for ppc64le
Setting /usr/bin/qemu-m68k-static as binfmt interpreter for m68k
Setting /usr/bin/qemu-mips-static as binfmt interpreter for mips
Setting /usr/bin/qemu-mipsel-static as binfmt interpreter for mipsel
Setting /usr/bin/qemu-mipsn32-static as binfmt interpreter for mipsn32
Setting /usr/bin/qemu-mipsn32el-static as binfmt interpreter for mipsn32el
Setting /usr/bin/qemu-mips64-static as binfmt interpreter for mips64
Setting /usr/bin/qemu-mips64el-static as binfmt interpreter for mips64el
Setting /usr/bin/qemu-sh4-static as binfmt interpreter for sh4
Setting /usr/bin/qemu-sh4eb-static as binfmt interpreter for sh4eb
Setting /usr/bin/qemu-s390x-static as binfmt interpreter for s390x
Setting /usr/bin/qemu-aarch64-static as binfmt interpreter for aarch64
Setting /usr/bin/qemu-aarch64_be-static as binfmt interpreter for aarch64_be
Setting /usr/bin/qemu-hppa-static as binfmt interpreter for hppa
Setting /usr/bin/qemu-riscv32-static as binfmt interpreter for riscv32
Setting /usr/bin/qemu-riscv64-static as binfmt interpreter for riscv64
Setting /usr/bin/qemu-xtensa-static as binfmt interpreter for xtensa
Setting /usr/bin/qemu-xtensaeb-static as binfmt interpreter for xtensaeb
Setting /usr/bin/qemu-microblaze-static as binfmt interpreter for microblaze
Setting /usr/bin/qemu-microblazeel-static as binfmt interpreter for microblazeel
Setting /usr/bin/qemu-or1k-static as binfmt interpreter for or1k
```

**Describe the results you received:**

List of different architectures that works perfectly

**Describe the results you expected:**

The i386 arch

**Environment:**

* QEMU version:
* Container application: Docker

**Output of `docker version`, `podman version` or `singularity version`**

```
docker version                    ✔  10066  17:36:04
Client: Docker Engine - Community
 Version:           19.03.1
 API version:       1.40
 Go version:        go1.12.5
 Git commit:        74b1e89e8a
 Built:             Thu Jul 25 21:17:37 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.1
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.5
  Git commit:       74b1e89e8a
  Built:            Thu Jul 25 21:27:55 2019
  OS/Arch:          linux/amd64
  Experimental:     true
 containerd:
  Version:          v1.2.7.m
  GitCommit:        85f6aa58b8a3170aec9824568f7a31832878b603.m
 runc:
  Version:          1.0.0-rc8
  GitCommit:        425e105d5a03fabd737a126ad93d62a9eeede87f
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

**Additional information optionally:**

**Comment by junaruga** [comment]
@vk496 good point! thanks for the feedback!

Certainly `/usr/bin/qemu-i386-static` is not included in the result of `docker run --rm --privileged multiarch/qemu-user-static --reset -p yes `.
But it actually works.

Which kind of Linux distribution's i386 container do you want to run?

If you want to run ubuntu's i386 container image, using `ubuntu/ image` image is good.
Here is the i386 's case with the i386 image: https://hub.docker.com/r/i386/ubuntu/ image.

You can refer it.
https://github.com/junaruga/ci-multi-arch-test
https://travis-ci.org/junaruga/ci-multi-arch-test/jobs/567486350

`file` command shows `32-bit` for the compiled binary on the environment.
`bin/hello` binary (C program to identity the environment by C programs) shows 32-bit.

```
$ file bin/hello
bin/hello: ELF 32-bit LSB shared object, Intel 80386, version 1 (SYSV), dynamically linked, interpreter /lib, for GNU/Linux 3.2.0, BuildID[sha1]=48eb3582abea27022b746ae6587bda9767896eaf, not stripped

$ bin/hello
Hello World!
Endian Type: Little-endian
Bit: 32-bit
Sizeof {int, long, long long, void*, size_t, off_t}: {4, 4, 8, 4, 4, 4}
```

When the point is `uname` command shows `x86_64`, but it can be actually i386 environment depending on the environment.
Because there are 2 types of architecture (architecture by `uname` command and actual architecture such as used as a deb or RPM package name), though I does not understand it well.
Same CPU type's 32-bit binary can work on 64-bit host environment.

If you want to run fedora, it does not have i386 image on both DockerHub and official container repo.
https://hub.docker.com/_/fedora
https://registry.fedoraproject.org/repo/fedora/tags/

**Comment by junaruga** [comment]
CentOS has the i386 image.
https://hub.docker.com/_/centos/

**Comment by junaruga** [comment]
Searched keywords: i386, i686, Intel 32-bit

**Comment by vk496** [comment]
Thanks for your reply! I was interesting in compile native i386 code.

It was recently added with the https://github.com/docker/buildx/issues/128 petition.

**Comment by junaruga** [comment]
Sure. Good news from buildx. I like docker buildx too. :)
